### ISSUE TITLE
Definición datos Loomies, LoomieBalls, Items

### ISSUE THREAD

**Issue by Woynert** [PedroChaparro/loomies-backend#28]
- [x] Loomies: Definir salud, defensa, y daño base.
- [x] Pokeballs: Tipos y probabilidad de captura.
- [x] Items aplicables a Loomies: Contexto, efectos.

Está información puede encontrarse en Notion [Pokemon Data](https://www.notion.so/Pok-mon-Data-6ec1df629ced40b29ce6597d4642a97e).

**Comment by SilviaPabon** [comment]
Vale, revisé la info de notion y la veo muy bien. Apruebo. Supongo que si todos aprobamos este issue pasaría a done no?

**Comment by PedroChaparro** [comment]
La única duda que tengo es sobre manejar dos tipos en los Loomies, por ejemplo, en Figma solo mostramos un tipo en la lista de Loomies del jugador, aunque cambiar eso es lo de menos, ¿Qué opinan @SilviaPabon y @andres123dbh sobre los Loomies con dos tipos?
