### ISSUE TITLE
Login endpoint: Mail shouldn't be case sensitive

### ISSUE THREAD

**Issue by Woynert** [PedroChaparro/loomies-backend#52]
If you signed in as ```user@mail.com``` submitting ```User@mail.com``` will be rejected.

**Comment by PedroChaparro** [comment]
Will you fix this @Woynert?

**Comment by Woynert** [comment]
If no one takes it by the time I finish [feat/map3d](https://github.com/PedroChaparro/loomies-mobile/tree/feat/map3d).

**Comment by PedroChaparro** [comment]
I'll fix this now while fixing the front-end side issues.
